language: r
sudo: required
cache: packages
warnings_are_errors: false
r_packages:
- ade4
- bayesm
- Cairo
- dplyr
- energy
- FD
- gcookbook
- GGally
- ggplot2
- ggrepel
- hrbrthemes
- Hmisc
- intergraph
- knitr
- lme4
- maptree
- MASS
- Matrix
- memoise
- minet
- mixOmics
- moments
- network
- qvalue
- reshape2
- rmarkdown
- robustbase
- rpart
- scales
- survival
- tgp
- Rtsne
- tidyr
- vegan
- WGCNA
bioc_packages:
- BiocInstaller
- DESeq2
- phyloseq
r_github_packages:
- cran/RUnit
- microbiome/microbiome
- zdk123/SpiecEasi
- briatte/ggnet
- earlywarningtoolbox/earlywarnings-R/earlywarnings
- jimhester/covr

env:
  global:
  - WARNINGS_ARE_ERRORS=1
  #- r_build_args: "--no-build-vignettes --no-manual --no-resave-data"
  #- r_check_args: "--no-build-vignettes --no-manual --as-cran"
  #- r_build_args: "--no-manual --no-resave-data"
  #- r_check_args: "--no-manual --as-cran"
  - r_build_args: "--no-resave-data"
  - r_check_args: "--as-cran"    
  - GITHUB_REPO: microbiome/microbiome
  - secure: kuJcKMx91ikYgbamYDep0b/44kXiHCJU5vn832tVWMm9VEYNqnOtfiWrJinFcwcTNsoVbQvH07xz1VobSFCsGn6bjxxAoM3WLe34+SWp8eWiZ8GQHU4tsVcxCJw+ZTzSS+cLs+JguQs+WCKU/0QOWRY77fUbBQg6v7B0z2Wy8N0=
before_install:
- pip install --user codecov
#- chmod 755 ./.deploy.sh
- sudo apt-get install -y tcl tk tk-dev
- sudo apt-get install -y libmagick++-dev
#script:
#

after_success:
  # - bash <(curl -s https://codecov.io/bash) 
  - Rscript -e 'covr::codecov()'
  
#- bash ./.push_to_master # Not ready: sync successful devel to master
# - bash ./.deploy.sh # Something broken
