language: r
r:
- devel
- release
- oldrel
- 3.3.3
- 3.3.2
- 3.3.1
- 3.3.0
- 3.2.5
- 3.2.4
- 3.2.3
- 3.2.2
- 3.2.1
- 3.2.0
- 3.1.3
- 3.1.2
- 3.1.1
- 3.1.0
- 3.0.3
sudo: required
cache: packages
warnings_are_errors: false
r_packages:
- dplyr
- ggplot2
- reshape2
- Rtsne
- scales
- tidyr
- vegan
bioc_packages:
- BiocInstaller
- phyloseq
r_github_packages:
- cran/RUnit
- jimhester/covr
env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - r_build_args: "--no-resave-data"
  - r_check_args: "--as-cran"    
  - GITHUB_REPO: microbiome/microbiome
  - secure: kuJcKMx91ikYgbamYDep0b/44kXiHCJU5vn832tVWMm9VEYNqnOtfiWrJinFcwcTNsoVbQvH07xz1VobSFCsGn6bjxxAoM3WLe34+SWp8eWiZ8GQHU4tsVcxCJw+ZTzSS+cLs+JguQs+WCKU/0QOWRY77fUbBQg6v7B0z2Wy8N0=
before_install:
- pip install --user codecov
- sudo apt-get install -y tcl tk tk-dev
- sudo apt-get install -y libmagick++-dev
after_success:
  - Rscript -e 'covr::codecov()'
  
